### ISSUE TITLE
the package does not recognize images from other sources

### ISSUE THREAD

**Issue by GeneralWinter101** [femioladeji/react-slideshow#120]
I've been working on this for two days now, I tried every way known to me to link my own images to the carousel, including finally uploading images to an external google drive and adding their links to the source table.  Attached you will see a screen shot of where I'm currently at and the result.

![image](https://user-images.githubusercontent.com/66372949/102606857-b4eea200-4127-11eb-9a26-3f27649fa9b3.png)
![image](https://user-images.githubusercontent.com/66372949/102606912-c3d55480-4127-11eb-993c-6be112a3ca90.png)

One other thing: this package requires numerous additional dependencies to be installed.  I installed all of them by hand as they popped up.  Maybe this is something that could be changed in the future.

**Comment by femioladeji** [comment]
@GeneralWinter101 did you import the `css`. You can follow this [sample](https://codesandbox.io/s/serene-lalande-yjmol).

As regards the dependency, they are mostly dev dependencies, they won't be installed in production. If you're still having issues setting it up can you please create a small example on [https://codesandbox.io/](https://codesandbox.io/s/serene-lalande-yjmol) so that I can have a better look
